# Generated by Django 2.2.6 on 2019-11-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadent', '0003_auto_20191118_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=''),
        ),
    ]
